[build]
  command = "npm run build"
  publish = "./"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  memory = 1024
  timeout = 30

# Add these new sections for image optimization
[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
  quality = 85
  metadata = "none"
