[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
  quality = 85
  metadata = "none"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native"]

[functions."*"]
  memory = 1024
  timeout = 30
  included_files = ["assets/css/**"]

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
