[build]
  command = "cd account/app && npm install && npm run build"
  publish = "account/app/dist"
  functions = "account/app/netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  memory = 1024
  timeout = 30

[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true
  quality = 85
  metadata = "none"

[[redirects]]
  from = "/account/app/*"
  to = "/account/app/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
