[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
  quality = 85
  metadata = "none"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native"]

[functions."*"]
  memory = 1024
  timeout = 30
  included_files = ["assets/css/**"]

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Application specific redirects
[[redirects]]
from = "/account/app/*"
to = "/account/app/:splat"
status = 200


# Main page redirect
[[redirects]]
  from = "/"
  to = "/account/app"
  status = 301
  force = true

# Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
