[build]
  command = "npm run build"
  publish = "./"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  memory = 1024
  timeout = 30

# Image optimization settings
[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
  quality = 85
  metadata = "none"

# Custom headers for better cache control
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
