[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://cdn.tailwindcss.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.tiny.cloud https://cdnjs.cloudflare.com; img-src 'self' data: https://res.cloudinary.com https://raw.githubusercontent.com; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdn.tiny.cloud https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; frame-src 'none'; connect-src 'self' https://*.netlify.com https://api.replicate.com; font-src 'self' https://fonts.gstatic.com; object-src 'none'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
